#!/bin/sh


echo "\n----------------------"
export PATH_TO_FX=/usr/share/openjfx/lib
alias beast="java --module-path $PATH_TO_FX --add-modules javafx.controls -jar /files/BDMM-Prime.jar"

echo "\e[94mHello investigators, we are the Phylodynamics team.\n" | pv -qL 20


echo "Now, let’s run our phylodynamic analysis." | pv -qL 40 

while true; do
    read -p "Type Yes to start the analysis" yn
        case $yn in
            [Yy]* )  echo "\n We will use BEAST2. \e[0m";
                     beast /files/beaver.xml;
            echo "\n\e[94mYou can find the results of the analysis in your CONFIDENTIAL folder. First, open the file Figure_beaver_mcc_tree1.tiff";
                     break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference? They want answers to the origin and speed of disease transmission of MOO-vi. Continue to step 7."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "This is referred to as the maximum clade credibility or MCC tree. It is an estimate of the total probability of the given tree topology. Each tip represents a sequence and the branches...
      Can you make conclusions about the transmission dynamics of the disease between beavers?" | pv -qL 40 


echo "\nPlease, continue to the final step.";
echo "\e[0m" 


