services:
  step0:
    build: step0_epi_data/
    command:
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step0_epi_data/files:/files/

  step1:
    build: step1_sequencing/
    command:
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step1_sequencing/files:/files/

  step2:
    build: step2_alignment/
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    stdin_open: true 
    tty: true
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step2_alignment/files:/files/

  # step2:
  #   build: step3_data_filtering/
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       echo "Go to the Exec panel and type sh start --->" 
  #       sleep infinity
    # environment:
    #   - DISPLAY=${DISPLAY}
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # network_mode: host
