#!/bin/sh


echo "\n----------------------"
echo "\e[94mWelcome back investigators, thrilled that you are still with us.\n" | pv -qL 20


echo "Now that we have covered some basics of the phylodynamic framework components, let's define yours for this epidemic.
\nUsually, we would use BEAUTI, an interface associated to the BEAST2 software, in which you can import data and set up phylodynamic analyses. However, mastering it can be quite time-consuming and with the conference this afternoon, time is tight. So let's keep it old school and work with paper sheets ;-)" | pv -qL 40 

echo "\n";

while true; do
    read -p "Can you see the paper sheets on your table? (y/n) " yn
        case $yn in
            [Yy]* ) echo "\nGreat! Each sheet represents a component of a phylodynamic framework.";
                    echo "Now that you got some background, you will try to link them together. "; break;;
            [Nn]* ) echo "\nMhumm, are you sure? Take a closer look, they are right there."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\n";

echo "You should have the following paper sheets:
\n- Orange: data components - alignment, sequence, sample type, sample dates.
\n- Blue: Model components - substitution model, molecular clock model and multi-type birth-death model.
\n- Green: Parameter components - origin, sampling proportion, becoming unifectious rate, etc.
\n- White: Definitions corresponding to the different components. " | pv -qL 40 

echo "\nPress any key to continue..."
read continue

echo "Please match each definition with its corresponding paper sheet. Ready, go!" | pv -qL 40 

echo "\nPress any key to continue..."
read continue

echo "Now, complete the missing links that connect all those components. Some have already been linked, try to find and link the missing ones. Ready, go!" | pv -qL 40 

echo "\nPress any key to continue..."
read continue

while true; do
    read -p "Do you wish to see the answer? (y/n) " yn
        case $yn in
            [Yy]* ) cp /files/model_beaver.pdf  /data/; echo "\nGo to your CONFIDENTIAL folder and open the file model_beaver.pdf. Here is what your phylodynamic framework should look like.";
                    break;;
            [Nn]* ) echo "\nAre you sure? Let's move on to step 4 to run this phylodynamic analysis."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\nPress any key to continue..."
read continue


echo "\nCongrats! Your phylodynamic framework is complete! Before moving onto step 4 to run your phylodynamic analysis, let's discuss prior and Bayesian inferences.";
echo "\e[0m" 