services:
  step1:
    build: step1_epi_data/
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    volumes:
      - /Desktop/CONFIDENTIAL_investigators:/data/
      - ./step1_epi_data/files:/files/
      #- /Desktop/CONFIDENTIAL_investigators:/data/
      ## - ./step1_epi_data/files:/files/
      - ./step1_epi_data:/app/
    container_name: B_Step1_Epi_data

  step2:
    build: step2_sequencing/
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    stdin_open: true 
    tty: true
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step2_sequencing/files:/files/
      - ./step2_sequencing:/app/
    container_name: B_Step2_Sequencing

  step3:
    build: step3_model_design/
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    stdin_open: true 
    tty: true
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step3_model_design/files:/files/
      - ./step3_model_design:/app/
    container_name: B_Step3_Model_design

  step4:
    build: step4_beast_analysis/
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo " ---> Go to the Exec panel and type START" 
        sleep infinity
    stdin_open: true 
    tty: true
    volumes:
      - ./CONFIDENTIAL_investigators:/data/
      - ./step4_beast_analysis/files:/files/
      - ./step4_beast_analysis:/app/
    container_name: B_Step4_BEAST2_analysis

  # docker compose up -d
