---
title: "New outbreak in Moose"
author: "SVEPM Moose Health Authority"
date: "2024-01-25"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Define path
setwd("step0_epi_data/")

## Library
library(dplyr)
library(ggplot2)
library(lubridate)
library(sf)
library(RColorBrewer)
```

## New outbreak in Moose

We have received several reports of a new disease in mooses The quick spread across Sweden and the high letality of the disease ....

Here you can find a summary of the reported cases so far:

```{r summary}

## Load epi data
epi_data <- read.csv("epi-data.csv", sep=";")

summary(epi_data)


Sys.setlocale("LC_TIME", "C") #to convert in English
epi_data$Observation.date <- as.Date(epi_data$Observation.date, format="%d/%m/%Y")

epi_data$Country <- as.factor(epi_data$Country)

# Keep only those between 2013 and 2015 and remove those with NA
epi_data <- epi_data[epi_data$Observation.date < "2015-12-31",]
epi_data <- epi_data[epi_data$Observation.date > "2013-01-01",]
epi_data <- epi_data[complete.cases(epi_data$Observation.date),]

# Add human in the column
epi_data$Species_new <- ifelse(epi_data$Species =="Camelidae (Unidentified)", "Camel", "Human")
epi_data$Species_new <- as.factor(epi_data$Species_new)

summary(epi_data$Observation.date)

summary(epi_data$Species_new)


summary(epi_data$Country)

tab <- epi_data %>% group_by(Country, Species_new) %>% summarize(count = n())


```


## Plots

And some plots from out team prepared for your investigation:
  
```{r plot, echo=FALSE}

cases_temp <- epi_data %>%  
  ggplot(aes(x=Observation.date, fill=Species_new)) +
  geom_histogram(binwidth=20, alpha = 0.8, color = "gray20") +
  facet_wrap(~Species_new, ncol=1, strip.position="right") +
  ylab("Number of MERS-CoV cases") +
  theme_classic() +
  scale_x_date(limits = c(ymd("2013-01-01"), ymd("2015-12-31")), date_breaks = "1 month", date_labels = "%b %y", expand = c(0,0)) +
  scale_fill_brewer(palette = "Set2", name ="Species") +
  #scale_fill_manual(name = "", values = c("slategray1","peachpuff"), labels = c("Domestic" = "Poultry farm", "Wild" = "Wild bird")) +
  theme(legend.position="none",
        #legend.box = "horizontal",
        #legend.text = element_text(size = 12),
        panel.grid = element_blank(),
        panel.grid.major.x =  element_line(colour = "grey80", linewidth = 0.2, linetype = 2),
        strip.text = element_text(size = 12),
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size=12, angle = 45, hjust = 1)) 

cases_temp
```

