#!/bin/sh


echo "\n----------------------"
echo "\e[94mDear investigators, we have exciting news!\n" | pv -qL 20


echo "Our field epi vet team were able to take some samples from 174 beavers. We sent them to the sequencing lab and we have the results back!" | pv -qL 40 

cat /files/ascii_dna.txt


while true; do
    read -p "Would you like to look at the genetic sequences? (y/n) " yn
        case $yn in
            [Yy]* )  cp /files/beaver_10_164_na.fasta  /data/; echo "\nYou can find the FASTA file with the sequences in your CONFIDENTIAL folder. Just double click in the file for a quick visualization.";
                     break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference? They want answers to the origin and speed of disease transmission of MOO-vi. Continue to step 7."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\nPress any key to continue..."
read continue

echo "So this is what genetic sequences look like" | pv -qL 40 

cat /files/toy_example.fasta

echo "\nWe have a total of 174 sequences which are stored in a FASTA file. As you can see in this format you have the sequence name (sequence_id|host|date) following the > and the sequence of nucleotides below.
      \nWe are interested in the similarity between the sequences. More similar sequences are more likely to be part of the same transmission cluster. 
      \nTo achieve this, first, we must align the sequences to enable a meaningful comparison of nucleotide sites." | pv -qL 40 

echo "\n";

while true; do
    read -p "Would you like us to align the sequences? (y/n) " yn
    # Full alignemnt  will take around 15 min, running a small dataset with only 100 nt
        case $yn in
            [Yy]* )  echo "\nWe will use MAFFT, a common software alignment to run the multiple sequence alignment.\e[0m";
                     "/usr/local/bin/mafft" --thread 8 --auto "/files/beaver_10_164_na.fasta" > "/data/aligned_small.fasta";
            echo "\n\e[94mAlignment completed! You can find the FASTA file with the aligned sequences in your CONFIDENTIAL folder. Just double click in the file for a quick visualization.";
                     break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference to report your conclusions? Continue to step 5."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\nCan you notice the difference compared to the unaligned sequences?" | pv -qL 40 

echo "\nPress any key to continue...\n"
read continue

echo "Wait... It appears that some sequences are considerably shorter than others. Can you identify them?
      \nThese shorter sequences might not be very informative for our analysis. Although there isn't a specific threshold length, we'll apply a percentage coverage filter to remove them." | pv -qL 40 

# Share histogram with completeness data, ask for percentage to filter
# Filter with R script

echo "\nPress any key to continue...\n"
read continue

echo "\nGreat, the genetic sequences have been processed! Before proceeding to step 3, let's review some details about the phylodynamic framework.";
echo "\e[0m" 
