#!/bin/sh


echo "\n----------------------"
export PATH_TO_FX=/usr/share/openjfx/lib
alias beast="java --module-path $PATH_TO_FX --add-modules javafx.controls -jar /files/BDMM-Prime.jar"

echo "\e[94mHello investigators, we are the BEAST2 team, ready to help you run your phylodynamic analysis with our software.\n" | pv -qL 20


echo "Now that you have defined your phylodynamic framework, let’s run your analysis." | pv -qL 40 

while true; do
    read -p "Ready to start your analysis? (y/n) " yn
        case $yn in
            [Yy]* )  echo "Running BEAST2... \e[0m";
                     beast /files/moose.xml;
            echo "\n\e[94mAnalysis completed! Above you will see BEAST2 running your analysis."; 
            echo "\nThe screen shows you XXX"; break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference to report your conclusions? Continue to step 5."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\nPress any key to continue...\n"
read continue

while true; do
    read -p "Do you want to take a closer look a the inferred posterior trees? (y/n) " yn
        case $yn in
            [Yy]* )  cp /files/moose_mcc_tree.pdf  /data/; echo "\nYou can access the files in your CONFIDENTIAL_investigators folder. The file provided shows the summary tree from your inferred posterior trees.";
                     echo "Based on the summary tree, which conclusions can you draw about the transmission dynamics of the disease between mooses and humans?"; break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference to report your conclusions? Continue to step 5."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done


echo "\nPress any key to continue..."
read continue

while true; do
    read -p "Now, do you want to take a closer look a the inferred posterior model parameters? (y/n) " yn
        case $yn in
            [Yy]* )  cp /files/moose.log  /data/; echo "\nYou can access the log file with the inferred parameters in your CONFIDENTIAL_investigators folder. Open it with Tracer software.";
                     echo "On the left panel, you will see XXXX"; break;;
            [Nn]* ) echo "\nOk. Are then you ready for the press conference to report your conclusions? Continue to step 5."; exit;;
            * ) echo "\nPlease answer yes or no.";;
        esac
done

echo "\nPress any key to continue..."
read continue


echo "\nWell, it seems that now you have all information inferred from your genetic sequences to report your conclusions to the press conference, continue to the final step ;-)";
echo "\e[0m" 

